name: Feature request
description: Suggest something useful.
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Problem / motivation
  - type: textarea
    attributes:
      label: Proposed API
